# Generated by Django 3.2.12 on 2022-06-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='simple one line text', max_length=100, verbose_name='DESCRIPTON')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('description', models.CharField(blank=True, help_text='Simple one line text', max_length=100, verbose_name='DESCRIPTION')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m', verbose_name='IMAGE')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED_AT')),
                ('like', models.PositiveSmallIntegerField(default=0, verbose_name='LIKE')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.category')),
                ('tags', models.ManyToManyField(blank=True, to='blogapp.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED_AT')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
    ]
